/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Professional } from "./Professional";
import { ProfessionalCountArgs } from "./ProfessionalCountArgs";
import { ProfessionalFindManyArgs } from "./ProfessionalFindManyArgs";
import { ProfessionalFindUniqueArgs } from "./ProfessionalFindUniqueArgs";
import { DeleteProfessionalArgs } from "./DeleteProfessionalArgs";
import { ProfessionalService } from "../professional.service";
@graphql.Resolver(() => Professional)
export class ProfessionalResolverBase {
  constructor(protected readonly service: ProfessionalService) {}

  async _professionalsMeta(
    @graphql.Args() args: ProfessionalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Professional])
  async professionals(
    @graphql.Args() args: ProfessionalFindManyArgs
  ): Promise<Professional[]> {
    return this.service.professionals(args);
  }

  @graphql.Query(() => Professional, { nullable: true })
  async professional(
    @graphql.Args() args: ProfessionalFindUniqueArgs
  ): Promise<Professional | null> {
    const result = await this.service.professional(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Professional)
  async deleteProfessional(
    @graphql.Args() args: DeleteProfessionalArgs
  ): Promise<Professional | null> {
    try {
      return await this.service.deleteProfessional(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
