/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProfessionalService } from "../professional.service";
import { ProfessionalCreateInput } from "./ProfessionalCreateInput";
import { Professional } from "./Professional";
import { ProfessionalFindManyArgs } from "./ProfessionalFindManyArgs";
import { ProfessionalWhereUniqueInput } from "./ProfessionalWhereUniqueInput";
import { ProfessionalUpdateInput } from "./ProfessionalUpdateInput";

export class ProfessionalControllerBase {
  constructor(protected readonly service: ProfessionalService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Professional })
  async createProfessional(
    @common.Body() data: ProfessionalCreateInput
  ): Promise<Professional> {
    return await this.service.createProfessional({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Professional] })
  @ApiNestedQuery(ProfessionalFindManyArgs)
  async professionals(@common.Req() request: Request): Promise<Professional[]> {
    const args = plainToClass(ProfessionalFindManyArgs, request.query);
    return this.service.professionals({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Professional })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async professional(
    @common.Param() params: ProfessionalWhereUniqueInput
  ): Promise<Professional | null> {
    const result = await this.service.professional({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Professional })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProfessional(
    @common.Param() params: ProfessionalWhereUniqueInput,
    @common.Body() data: ProfessionalUpdateInput
  ): Promise<Professional | null> {
    try {
      return await this.service.updateProfessional({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Professional })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProfessional(
    @common.Param() params: ProfessionalWhereUniqueInput
  ): Promise<Professional | null> {
    try {
      return await this.service.deleteProfessional({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
